# TCL File Generated by Component Editor 16.1
# Wed Mar 08 15:40:53 CET 2017
# DO NOT MODIFY


# 
# sobel_edge_detector "sobel_edge_detector" v1.0
# phm 2017.03.08.15:40:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module sobel_edge_detector
# 
set_module_property DESCRIPTION ""
set_module_property NAME sobel_edge_detector
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP ase
set_module_property AUTHOR phm
set_module_property DISPLAY_NAME sobel_edge_detector
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL altera_up_avalon_video_edge_detection
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file altera_up_avalon_video_edge_detection.vhd VHDL PATH EdgeDetection/altera_up_avalon_video_edge_detection.vhd TOP_LEVEL_FILE
add_fileset_file altera_up_edge_detection_data_shift_register.vhd VHDL PATH EdgeDetection/altera_up_edge_detection_data_shift_register.vhd
add_fileset_file altera_up_edge_detection_gaussian_smoothing_filter.vhd VHDL PATH EdgeDetection/altera_up_edge_detection_gaussian_smoothing_filter.vhd
add_fileset_file altera_up_edge_detection_hysteresis.vhd VHDL PATH EdgeDetection/altera_up_edge_detection_hysteresis.vhd
add_fileset_file altera_up_edge_detection_nonmaximum_suppression.vhd VHDL PATH EdgeDetection/altera_up_edge_detection_nonmaximum_suppression.vhd
add_fileset_file altera_up_edge_detection_pixel_info_shift_register.vhd VHDL PATH EdgeDetection/altera_up_edge_detection_pixel_info_shift_register.vhd
add_fileset_file altera_up_edge_detection_sobel_operator.vhd VHDL PATH EdgeDetection/altera_up_edge_detection_sobel_operator.vhd


# 
# parameters
# 
add_parameter WIDTH INTEGER 640 ""
set_parameter_property WIDTH DEFAULT_VALUE 640
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH DESCRIPTION ""
set_parameter_property WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end bypass bypass Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink in_data data Input 8
add_interface_port avalon_streaming_sink in_startofpacket startofpacket Input 1
add_interface_port avalon_streaming_sink in_endofpacket endofpacket Input 1
add_interface_port avalon_streaming_sink in_valid valid Input 1
add_interface_port avalon_streaming_sink in_ready ready Output 1


# 
# connection point avalon_streaming_source
# 
add_interface avalon_streaming_source avalon_streaming start
set_interface_property avalon_streaming_source associatedClock clock
set_interface_property avalon_streaming_source associatedReset reset
set_interface_property avalon_streaming_source dataBitsPerSymbol 8
set_interface_property avalon_streaming_source errorDescriptor ""
set_interface_property avalon_streaming_source firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_source maxChannel 0
set_interface_property avalon_streaming_source readyLatency 0
set_interface_property avalon_streaming_source ENABLED true
set_interface_property avalon_streaming_source EXPORT_OF ""
set_interface_property avalon_streaming_source PORT_NAME_MAP ""
set_interface_property avalon_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_source out_data data Output 8
add_interface_port avalon_streaming_source out_startofpacket startofpacket Output 1
add_interface_port avalon_streaming_source out_endofpacket endofpacket Output 1
add_interface_port avalon_streaming_source out_valid valid Output 1
add_interface_port avalon_streaming_source out_ready ready Input 1

